version: "3"
services:
  crawler:
    container_name: crawler
    build: ./crawler
    command: bash -c "cd jpy_currency && python routine.py"
    volumes:
      - ./crawler:/app
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    links:
      - mongo:mongodb-service
    environment:
      - MONGO_URL=mongo:27017

  restful:
    container_name: restful
    build: ./restful
    # command: nodemon server.js
    volumes:
      - ./restful:/app
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - AUTH_URL=auth-service:9000
      - MONGO_URL=mongo:27017

  auth-service:
    container_name: auth-service
    build: ./auth
    volumes:
      - ./auth:/app
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "9000:9000"
    environment:
      - MONGO_URL=mongo:27017
      - JWT_SECRET=''
      - APP_ID=''
      - APP_SECRET=''
      - GOOGLE_CLIENT_ID=''
      - GOOGLE_CLIENT_SECRET=''
      - GOOGLE_CLIENT_CB=''
  web:
    container_name: web
    build: ./web
    volumes:
      - ./web:/app
    links:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongo:27017

  mongo:
    image: mongo:3.0.2
    volumes:
      - './data:/data/db'
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
