apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auth-deployment
    spec:
      containers:
      - image: victortsaitw12/d3-practice-auth
        imagePullPolicy: Always
        name: d3-practice-auth
        ports:
          - containerPort: 9000
        env:
          - name: APP_ID
            value: "843930439103568"
          - name: APP_SECRET
            value: "f6f3dd2a33f28dc3b493be80d7083b04"
          - name: JWT_SECRET
            value: "jwtsecretkey"
