apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: auth-deployment

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auth-deployment
    spec:
      containers:
      - image: victortsaitw12/d3-practice-auth:v2
        imagePullPolicy: Always
        name: d3-practice-auth
        ports:
          - containerPort: 9000
        env:
          - name: MONGO_URL
            value: "mongodb-service:27017"
          - name: APP_ID
            valueFrom:
              secretKeyRef:
                name: sensitive-data
                key: app_id
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: sensitive-data
                key: app_secret
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: sensitive-data
                key: jwt_secret
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: sensitive-data
                key: google_client_id
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: sensitive-data
                key: google_client_secret
