kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: mongo
  name: mongo-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
